USER 1200
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
#========================
# nholuong Distributor Configuration
#========================

EXPOSE 5553

COPY start-nholuong-grid-distributor.sh \
    /opt/bin/

COPY nholuong-grid-distributor.conf /etc/supervisor/conf.d/
