# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: nholuong/node-docker:4.0.0-beta-4-prerelease-20210517
    volumes:
      - ./assets:/opt/nholuong/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - nholuong-hub
    environment:
      - SE_EVENT_BUS_HOST=nholuong-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  nholuong-hub:
    image: nholuong/hub:4.0.0-beta-4-prerelease-20210517
    container_name: nholuong-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
