USER 1200

#========================
# nholuong Standalone Docker Configuration
#========================

EXPOSE 4444

COPY start-nholuong-grid-node-docker.sh \
    config.toml \
    /opt/bin/

COPY nholuong-grid-node-docker.conf /etc/supervisor/conf.d/

