USER 1200
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
#=================================
# nholuong Event Bus Configuration
#=================================

# Port where events are published
EXPOSE 4442
# Port where to subscribe for events
EXPOSE 4443
# Event Bus port
EXPOSE 5557

COPY start-nholuong-grid-eventbus.sh \
    /opt/bin/

COPY nholuong-grid-eventbus.conf /etc/supervisor/conf.d/
